spring:
  main:
    banner-mode: 'off'

server:
  port: ${http.port?:8080}


metrics:
  enabled: ${metrics.enabled?:true}
  logback: true
  jvm:   true
  sets: com.codahale.metrics.jvm.GarbageCollectorMetricSet,
    com.codahale.metrics.jvm.MemoryUsageGaugeSet,
    com.codahale.metrics.jvm.ThreadStatesGaugeSet


microservice:
  metrics:
    graphite:
      enabled: ${microservice.metrics.graphite.enabled?:true}
      port: ${microservice.metrics.graphite.port?:2003}
      host: ${microservice.metrics.graphite.host?:localhost}
      prefix: ${application.name}



endpoints:
  metrics:
    filter:
      enabled: false


auditing:
  enabled: ${auditing.enabled?:true}
  traceRequests: ${auditing.traceRequests?:true}
  source: ${application.name}
  consumer:
    baseUri:
      port: ${auditing.consumer.baseUri.port?:9000}
      host: ${auditing.consumer.baseUri.host?:localhost}
  exclusions:
    - /ping/ping

